name: Test build PR
on:
  pull_request:
    types: [opened, synchronize, reopened]
env:
  IMAGE_NAME: qdevice
  TAG: $GITHUB_SHA
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build and export to Docker
        uses: docker/build-push-action@v5
        with:
          context: .
          load: true
          tags: ${{ env.IMAGE_NAME}}:${{ env.TAG }}
      - name: Test
        run: |
          docker run --rm ${{ env.IMAGE_NAME}}:${{ env.TAG }}
